"""Map subcategory codes to their full names from the screenshots."""
from app.database import SessionLocal
from app.models.models import Subcategory

db = SessionLocal()

# Map code -> full name based on the screenshots
# Using pattern matching: code abbreviations map to names
code_to_name = {
    # Direct/obvious mappings
    "AIC": "Air Conditioner",
    "AT": "Appointment Time",
    "AUTH": "Authentication",
    "BC": "Bill Cancellation",
    "BCP": "Billing Complimentary Products",
    "BCS": "Billing Complimentary Sessions",
    "BDOBILLS": "Back Dating of Bills",
    "BOCFDP": "Billing Old Client Full Discount Package",
    "CAR": "Carpentry Service",
    "CAS": "Change of Address",
    "CC": "Confirmation Call",
    "CIW": "Civil Works",
    "CNA": "Campaign Not Applied",
    "CPDEND": "Close payments/Day end not Done",
    "DRB": "Dr Behaviour",
    "DRNC": "Dr Refferal Not Captured",
    "ECA": "Edits In Petty Cash",
    "ELS": "Electrical Services",
    "EMS": "Emergency Service",
    "EPC": "Employee/Friends/Family Campaign",
    "EQU": "Equipment",
    "Expriy": "Expriy",
    "FDB": "FD Behaviour",
    "GAT": "Gift Card Creation",
    "GCC": "Gift Card Creation",
    "HAS": "Hardware Support",
    "IABC": "Incorrect Campaign Application",
    "ICA": "Incorrect Campaign Application",
    "INCP": "Incorrect Name Captured for Product",
    "INCPKG": "Incorrect Name Captured for PKG/Session",
    "LOY": "Loyalty",
    "MNCP": "Missed Name Captures For Product",
    "MNCPKG": "Missed Name Captures PKG/Session",
    "MPR": "Multiple Package Refund",
    "NES": "Network Support",
    "OAS": "Office Administration Support",
    "OTPI": "OTP Issues",
    "OrderRepmnt": "Order Replacement",
    "Others": "Others",
    "PAS": "Painting Service",
    "PBC": "Product Bill Cancellation",
    "PCGLP": "Prepaid card/Gift card/Loyalty points",
    "PEC": "Pest Control",
    "PIS": "Pricing- Structure",
    "PMC": "Payment Mode Changes",
    "PNU": "Phone No Update",
    "PRJ": "Project Services",
    "PRO": "Procurment",
    "PRS": "Pantry Services",
    "PWM": "Plumbing & Water Management",
    "ProductConcern": "Product Concern",
    "REAT": "Real Estate Management",
    "REM": "Removal of Excess Payment",
    "REP": "Resource/Employee Addition/Transfer",
    "RF": "Refund",
    "Refund": "Refund Status",
    "SOS": "Software Support",
    "TCC": "Telephone",
    "TEL": "Telephone",
    "THFT": "Theft",
    "TR": "Order Tracking",
    "Treatment": "Treatment",
    "UAEP": "Uploading Adverse Event Picture",
    "UP": "Unfreeze Package",
    "VEP": "Validity Extention of Package",
    "WAM": "Waste Management",
    "WC": "Wrong Consumption",
    "WE": "Wrong products ordered",
    "WRP": "Wrong Refund of Package",
    "WRPRODUCT": "Wrong refund of Product",
    "DrBehaviour": "Dr Behaviour",
    "FDBehaviour": "FD Behaviour",

    # BPM prefix codes
    "BPMAT": "BPM - Appointment Time",
    "BPMCC": "BPM - Confirmation Call",
    "BPMDRB": "BPM - Dr Behaviour",
    "BPMEAC": "BPM Escalation - Air Conditioner",
    "BPMEAO": "BPM Escalation - Adverse Outcomes",
    "BPMEAR": "BPM Escalation - Appointment reschedule",
    "BPMEAT": "BPM Escalation - Appointment Time",
    "BPMECC": "BPM Escalation - Confirmation Call",
    "BPMECRT": "BPM Escalation - CRT Behaviour",
    "BPMEDR": "BPM Escalation - Delivery Status",
    "BPMEDRB": "BPM Escalation - Dr Behaviour",
    "BPMEFDB": "BPM Escalation - FD Behaviour",
    "BPMEHI": "BPM Escalation - Hygiene issues",
    "BPMEL": "BPM Escalation - Loyalty",
    "BPMELP": "BPM Escalation - Loyalty Points",
    "BPMEN": "BPM Escalation - No Comments only rating",
    "BPMEO": "BPM Escalation - Others",
    "BPMEOS": "BPM Escalation - overall services",
    "BPMEP": "BPM Escalation - Products",
    "BPMEPR": "BPM Escalation - Pricing Quotation",
    "BPMEPS": "BPM Escalation - Payment related concerns",
    "BPMERF": "BPM Escalation - Refund",
    "BPMERS": "BPM Escalation - Less Than Desireable results",
    "BPMEST": "BPM Escalation - ST Behaviour",
    "BPMET": "BPM Escalation - Treatment",
    "BPMETMT": "BPM Escalation - Treatment",
    "BPMEWT": "BPM Escalation - Wait Time",
    "BPMEpq": "BPM Escalation - Pricing Quotation",
    "BPMFDB": "BPM - FD Behaviour",
    "BPMOTH": "BPM - Others",
    "BPMT": "BPM - Treatment",
    "BPMTFT": "BPM - Treatment",

    # DSAT prefix codes
    "DSATCAC": "Dsat - Air Conditioner",
    "DSATCAO": "Dsat - Adverse Outcomes",
    "DSATCAR": "Dsat - Appointment reschedule",
    "DSATCAT": "Dsat - Appointment Time",
    "DSATCCC": "Dsat - Confirmation Call",
    "DSATCCRT": "Dsat - CRT Behaviour",
    "DSATCDR": "Dsat - Delivery Status",
    "DSATCDRB": "Dsat - Dr Behaviour",
    "DSATCFDB": "Dsat - FD Behaviour",
    "DSATCHI": "Dsat - Hygiene issues",
    "DSATCL": "Dsat - Loyalty",
    "DSATCLP": "Dsat - Loyalty Points",
    "DSATCN": "Dsat - No Comments only rating",
    "DSATCO": "Dsat - Others",
    "DSATCOS": "Dsat - overall services",
    "DSATCP": "Dsat - Products",
    "DSATCPQ": "Dsat - Pricing Quotation",
    "DSATCPR": "Dsat - Pricing Quotation",
    "DSATCPS": "Dsat - Payment related concerns",
    "DSATCRF": "Dsat - Refund",
    "DSATCRS": "Dsat - Less Than Desireable results",
    "DSATCST": "Dsat - ST Behaviour",
    "DSATCT": "Dsat - Treatment",
    "DSATCTMT": "Dsat - Treatment",
    "DSATCWT": "Dsat - Wait Time",

    # FB (Facebook) prefix
    "FBAC": "Facebook - Air Conditioner",
    "FBAO": "Facebook - Adverse Outcomes",
    "FBAR": "Facebook - Appointment reschedule",
    "FBAT": "Facebook - Appointment Time",
    "FBC": "Facebook - Confirmation Call",
    "FBCC": "Facebook - Confirmation Call",
    "FBCRT": "Facebook - CRT Behaviour",
    "FBDR": "Facebook - Delivery Status",
    "FBDRB": "Facebook - Dr Behaviour",
    "FBFDB": "Facebook - FD Behaviour",
    "FBHI": "Facebook - Hygiene issues",
    "FBL": "Facebook - Loyalty",
    "FBLP": "Facebook - Loyalty Points",
    "FBN": "Facebook - No Comments only rating",
    "FBOS": "Facebook - overall services",
    "FBOTH": "Facebook - Others",
    "FBP": "Facebook - Products",
    "FBPKG": "Facebook - Full Body Package",
    "FBPQ": "Facebook - Pricing Quotation",
    "FBPR": "Facebook - Pricing Quotation",
    "FBPS": "Facebook - Payment related concerns",
    "FBRF": "Facebook - Refund",
    "FBRS": "Facebook - Less Than Desireable results",
    "FBST": "Facebook - ST Behaviour",
    "FBT": "Facebook - Treatment",
    "FBTFT": "Facebook - Treatment",
    "FBWT": "Facebook - Wait Time",

    # FDBK (Feedback) prefix
    "FDBKAC": "Feedback - Air Conditioner",
    "FDBKAO": "Feedback - Adverse Outcomes",
    "FDBKAR": "Feedback - Appointment reschedule",
    "FDBKCC": "Feedback - Confirmation Call",
    "FDBKCRT": "Feedback - CRT Behaviour",
    "FDBKDR": "Feedback - Delivery Status",
    "FDBKDRB": "Feedback - Dr Behaviour",
    "FDBKFDB": "Feedback - FD Behaviour",
    "FDBKHI": "Feedback - Hygiene issues",
    "FDBKLP": "Feedback - Loyalty Points",
    "FDBKLT": "Feedback - Less Than Desireable results",
    "FDBKNC": "Feedback - No Comments only rating",
    "FDBKOS": "Feedback - overall services",
    "FDBKOTH": "Feedback - Others",
    "FDBKPQ": "Feedback - Pricing Quotation",
    "FDBKPR": "Feedback - Pricing Quotation",
    "FDBKPROD": "Feedback - Products",
    "FDBKPS": "Feedback - Payment related concerns",
    "FDBKRF": "Feedback - Refund",
    "FDBKRS": "Feedback - Less Than Desireable results",
    "FDBKST": "Feedback - ST Behaviour",
    "FDBKT": "Feedback - Treatment",
    "FDBKTFT": "Feedback - Treatment",
    "FDBKWT": "Feedback - Wait Time",

    # FEED prefix
    "FEEDCOF": "Disappointing Response on Ezconnect",
    "FEEDDS": "Delivery Status",
    "FEEDOT": "Appointment convenience",
    "FEEDOTRS": "Less Than Desireable results",
    "FEEDWPO": "Wrong products ordered",
    "FEEDWPR": "Wrong products received",
    "FOTH": "FM Call - Others",

    # GFDBC (General Feedback Call) prefix
    "GFDBCAC": "General Feedback - Air Conditioner",
    "GFDBCAO": "General Feedback - Adverse Outcomes",
    "GFDBCAR": "General Feedback - Appointment reschedule",
    "GFDBCAT": "General Feedback - Appointment Time",
    "GFDBCCC": "General Feedback - Confirmation Call",
    "GFDBCCRT": "General Feedback - CRT Behaviour",
    "GFDBCDRB": "General Feedback - Dr Behaviour",
    "GFDBCFDB": "General Feedback - FD Behaviour",
    "GFDBCHI": "General Feedback - Hygiene issues",
    "GFDBCL": "General Feedback - Loyalty",
    "GFDBCLP": "General Feedback - Loyalty Points",
    "GFDBCN": "General Feedback - No Comments only rating",
    "GFDBCO": "General Feedback - Others",
    "GFDBCOS": "General Feedback - overall services",
    "GFDBCP": "General Feedback - Products",
    "GFDBCPQ": "General Feedback - Pricing Quotation",
    "GFDBCPR": "General Feedback - Pricing Quotation",
    "GFDBCPS": "General Feedback - Payment related concerns",
    "GFDBCRF": "General Feedback - Refund",
    "GFDBCRS": "General Feedback - Less Than Desireable results",
    "GFDBCST": "General Feedback - ST Behaviour",
    "GFDBCT": "General Feedback - Treatment",
    "GFDBCTMT": "General Feedback - Treatment",
    "GFDBCWT": "General Feedback - Wait Time",

    # GR (Google Review) prefix
    "GRAC": "Google Review - Air Conditioner",
    "GRAO": "Google Review - Adverse Outcomes",
    "GRAR": "Google Review - Appointment reschedule",
    "GRCC": "Google Review - Confirmation Call",
    "GRCRT": "Google Review - CRT Behaviour",
    "GRDR": "Google Review - Delivery Status",
    "GRDRB": "Google Review - Dr Behaviour",
    "GRFDB": "Google Review - FD Behaviour",
    "GRHI": "Google Review - Hygiene issues",
    "GRL": "Google Review - Loyalty",
    "GRLP": "Google Review - Loyalty Points",
    "GROS": "Google Review - overall services",
    "GROTH": "Google Review - Others",
    "GRP": "Google Review - Products",
    "GRPQ": "Google Review - Pricing Quotation",
    "GRPR": "Google Review - Pricing Quotation",
    "GRPS": "Google Review - Payment related concerns",
    "GRREFUND": "Google Review - Refund",
    "GRRS": "Google Review - Less Than Desireable results",
    "GRST": "Google Review - ST Behaviour",
    "GRTFT": "Google Review - Treatment",
    "GRWT": "Google Review - Wait Time",

    # INFO prefix
    "INFOAT": "Info - Appointment Time",
    "INFOCC": "Info - Confirmation Call",
    "INFORF": "Info - Refund",
    "INFOT": "Info - Treatment",

    # JD (Justdial) prefix
    "JDAT": "Justdial - Appointment Time",
    "JDDRB": "Justdial - Dr Behaviour",
    "JDFDB": "Justdial - FD Behaviour",
    "JDOTH": "Justdial - Others",
    "JDRF": "Justdial - Refund",
    "JDT": "Justdial - Treatment",
    "JDTFT": "Justdial - Treatment",

    # MS (Mouthshut) prefix
    "MSAC": "Mouthshut - Air Conditioner",
    "MSAO": "Mouthshut - Adverse Outcomes",
    "MSAR": "Mouthshut - Appointment reschedule",
    "MSAT": "Mouthshut - Appointment Time",
    "MSCC": "Mouthshut - Confirmation Call",
    "MSCRT": "Mouthshut - CRT Behaviour",
    "MSDR": "Mouthshut - Delivery Status",
    "MSDRB": "Mouthshut - Dr Behaviour",
    "MSFDB": "Mouthshut - FD Behaviour",
    "MSHI": "Mouthshut - Hygiene issues",
    "MSL": "Mouthshut - Loyalty",
    "MSLP": "Mouthshut - Loyalty Points",
    "MSN": "Mouthshut - No Comments only rating",
    "MSO": "Mouthshut - Others",
    "MSOS": "Mouthshut - overall services",
    "MSP": "Mouthshut - Products",
    "MSPQ": "Mouthshut - Pricing Quotation",
    "MSPR": "Mouthshut - Pricing Quotation",
    "MSPS": "Mouthshut - Payment related concerns",
    "MSRF": "Mouthshut - Refund",
    "MSRS": "Mouthshut - Less Than Desireable results",
    "MSST": "Mouthshut - ST Behaviour",
    "MST": "Mouthshut - Treatment",
    "MSTF": "Mouthshut - Treatment",
    "MSWT": "Mouthshut - Wait Time",

    # PROD (Products) prefix
    "PRODAC": "Products - Air Conditioner",
    "PRODAO": "Products - Adverse Outcomes",
    "PRODAR": "Products - Appointment reschedule",
    "PRODAT": "Products - Appointment Time",
    "PRODCC": "Products - Confirmation Call",
    "PRODCRT": "Products - CRT Behaviour",
    "PRODDR": "Products - Delivery Status",
    "PRODDRB": "Products - Dr Behaviour",
    "PRODFDB": "Products - FD Behaviour",
    "PRODHI": "Products - Hygiene issues",
    "PRODL": "Products - Loyalty",
    "PRODLP": "Products - Loyalty Points",
    "PRODN": "Products - No Comments only rating",
    "PRODOS": "Products - overall services",
    "PRODP": "Products - Products",
    "PRODPQ": "Products - Pricing Quotation",
    "PRODPR": "Products - Pricing Quotation",
    "PRODPS": "Products - Payment related concerns",
    "PRODRS": "Products - Less Than Desireable results",
    "PRODST": "Products - ST Behaviour",
    "PRODTMT": "Products - Treatment",
    "PRODWT": "Products - Wait Time",

    # SE (Support Emails) prefix
    "SEAC": "Support Emails - Air Conditioner",
    "SEAO": "Support Emails - Adverse Outcomes",
    "SEAR": "Support Emails - Appointment reschedule",
    "SEAT": "Support Emails - Appointment Time",
    "SECC": "Support Emails - Confirmation Call",
    "SECRT": "Support Emails - CRT Behaviour",
    "SEDR": "Support Emails - Delivery Status",
    "SEDRB": "Support Emails - Dr Behaviour",
    "SEFDB": "Support Emails - FD Behaviour",
    "SEHI": "Support Emails - Hygiene issues",
    "SEL": "Support Emails - Loyalty",
    "SELP": "Support Emails - Loyalty Points",
    "SEN": "Support Emails - No Comments only rating",
    "SEO": "Support Emails - Others",
    "SEOS": "Support Emails - overall services",
    "SEP": "Support Emails - Products",
    "SEPQ": "Support Emails - Pricing Quotation",
    "SEPR": "Support Emails - Pricing Quotation",
    "SEPS": "Support Emails - Payment related concerns",
    "SERF": "Support Emails - Refund",
    "SERS": "Support Emails - Less Than Desireable results",
    "SES": "Support Emails - ST Behaviour",
    "SEST": "Support Emails - ST Behaviour",
    "SET": "Support Emails - Treatment",
    "SETMT": "Support Emails - Treatment",
    "SEWT": "Support Emails - Wait Time",

    # SFDBK (Service Feedback) prefix
    "SFDBKAC": "Service Feedback - Air Conditioner",
    "SFDBKAO": "Service Feedback - Adverse Outcomes",
    "SFDBKAR": "Service Feedback - Appointment reschedule",
    "SFDBKAT": "Service Feedback - Appointment Time",
    "SFDBKCC": "Service Feedback - Confirmation Call",
    "SFDBKCRT": "Service Feedback - CRT Behaviour",
    "SFDBKDR": "Service Feedback - Delivery Status",
    "SFDBKDRB": "Service Feedback - Dr Behaviour",
    "SFDBKFDB": "Service Feedback - FD Behaviour",
    "SFDBKHI": "Service Feedback - Hygiene issues",
    "SFDBKL": "Service Feedback - Loyalty",
    "SFDBKLP": "Service Feedback - Loyalty Points",
    "SFDBKN": "Service Feedback - No Comments only rating",
    "SFDBKO": "Service Feedback - Others",
    "SFDBKOS": "Service Feedback - overall services",
    "SFDBKP": "Service Feedback - Products",
    "SFDBKPQ": "Service Feedback - Pricing Quotation",
    "SFDBKPR": "Service Feedback - Pricing Quotation",
    "SFDBKPS": "Service Feedback - Payment related concerns",
    "SFDBKRF": "Service Feedback - Refund",
    "SFDBKRS": "Service Feedback - Less Than Desireable results",
    "SFDBKST": "Service Feedback - ST Behaviour",
    "SFDBKT": "Service Feedback - Treatment",
    "SFDBKTMT": "Service Feedback - Treatment",
    "SFDBKWT": "Service Feedback - Wait Time",

    # SMS prefix - keep as SMS
    # TSC (Treatment Satisfaction call) prefix
    "TSCAC": "TSC - Air Conditioner",
    "TSCAO": "TSC - Adverse Outcomes",
    "TSCAR": "TSC - Appointment reschedule",
    "TSCAT": "TSC - Appointment Time",
    "TSCCC": "TSC - Confirmation Call",
    "TSCCRT": "TSC - CRT Behaviour",
    "TSCDR": "TSC - Delivery Status",
    "TSCDRB": "TSC - Dr Behaviour",
    "TSCFDB": "TSC - FD Behaviour",
    "TSCHI": "TSC - Hygiene issues",
    "TSCL": "TSC - Loyalty",
    "TSCLP": "TSC - Loyalty Points",
    "TSCN": "TSC - No Comments only rating",
    "TSCO": "TSC - Others",
    "TSCOS": "TSC - overall services",
    "TSCP": "TSC - Products",
    "TSCPQ": "TSC - Pricing Quotation",
    "TSCPR": "TSC - Pricing Quotation",
    "TSCPS": "TSC - Payment related concerns",
    "TSCRF": "TSC - Refund",
    "TSCRS": "TSC - Less Than Desireable results",
    "TSCST": "TSC - ST Behaviour",
    "TSCT": "TSC - Treatment",
    "TSCTMT": "TSC - Treatment",
    "TSCWT": "TSC - Wait Time",

    # TW (Twitter) prefix
    "TWAC": "Twitter - Air Conditioner",
    "TWAO": "Twitter - Adverse Outcomes",
    "TWAR": "Twitter - Appointment reschedule",
    "TWAT": "Twitter - Appointment Time",
    "TWCRT": "Twitter - CRT Behaviour",
    "TWDR": "Twitter - Delivery Status",
    "TWDRB": "Twitter - Dr Behaviour",
    "TWFDB": "Twitter - FD Behaviour",
    "TWHI": "Twitter - Hygiene issues",
    "TWL": "Twitter - Loyalty",
    "TWLP": "Twitter - Loyalty Points",
    "TWN": "Twitter - No Comments only rating",
    "TWOS": "Twitter - overall services",
    "TWOTH": "Twitter - Others",
    "TWP": "Twitter - Products",
    "TWPQ": "Twitter - Pricing Quotation",
    "TWPR": "Twitter - Pricing Quotation",
    "TWPS": "Twitter - Payment related concerns",
    "TWRF": "Twitter - Refund",
    "TWRS": "Twitter - Less Than Desireable results",
    "TWST": "Twitter - ST Behaviour",
    "TWT": "Twitter - Treatment",
    "TWTFT": "Twitter - Treatment",
    "TWWT": "Twitter - Wait Time",

    # WEB (Website) prefix
    "WEBAC": "Website - Air Conditioner",
    "WEBAO": "Website - Adverse Outcomes",
    "WEBAR": "Website - Appointment reschedule",
    "WEBCRT": "Website - CRT Behaviour",
    "WEBDR": "Website - Delivery Status",
    "WEBHI": "Website - Hygiene issues",
    "WEBL": "Website - Loyalty",
    "WEBLP": "Website - Loyalty Points",
    "WEBN": "Website - No Comments only rating",
    "WEBOS": "Website - overall services",
    "WEBP": "Website - Products",
    "WEBPQ": "Website - Pricing Quotation",
    "WEBPR": "Website - Pricing Quotation",
    "WEBPS": "Website - Payment related concerns",
    "WEBRS": "Website - Less Than Desireable results",
    "WEBST": "Website - ST Behaviour",
    "WEBWT": "Website - Wait Time",
    "WECC": "Website - Confirmation Call",
    "WEDRB": "Website - Dr Behaviour",
    "WEFDB": "Website - FD Behaviour",
    "WEGAT": "Website - Appointment Time",
    "WEOTH": "Website - Others",
    "WEREFUND": "Website - Refund",
    "WETFT": "Website - Treatment",

    # Zenoti prefix
    # ZF = Zenoti-Finance, ZO = Zenoti-Operational (already mapped as categories)

    # SMS prefix
    "SMS": "SMS",

    # Printing & Stationery
    "PIS": "Printing & Stationery",
}

updated = 0
for sub in db.query(Subcategory).all():
    if sub.code in code_to_name and sub.name == sub.code:
        sub.name = code_to_name[sub.code]
        updated += 1

db.commit()
print(f"Updated {updated} subcategory names")
print(f"Total subcategories: {db.query(Subcategory).count()}")

# Show some that still have code == name
still_code = db.query(Subcategory).filter(Subcategory.name == Subcategory.code).count()
print(f"Still using code as name: {still_code}")
db.close()
